name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Visual Studio Build Tools via Chocolatey
        shell: pwsh
        run: |
          $installDir = "C:\MyVS"
          choco install visualstudio2022buildtools --yes `
            --package-parameters "--installPath `"$installDir`" --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --passive --norestart --wait"

      - name: Build with MSBuild (Release|Win32)
        shell: cmd
        run: |
          call "C:\MyVS\VC\Auxiliary\Build\vcvars32.bat"
          msbuild ArcadeEssentials.sln /p:Configuration=Release /p:Platform=Win32 /m

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: Binaries
          path: ${{ github.workspace }}/build/*
